### PR TITLE
Introduced minimum N for matches

### PR DESCRIPTION
**Pull request by andrewpatto**
Not really tested - as I don't have any particular files with low N. But I think the logic is sound and we have no introduced any regression as the existing test suite is good.

This is to cope with ctTSO samples of poor quality where n is < 10

### CODE REVIEW

**Comment by alexiswl** [comment]
Thanks Andrew! Happy to just approve, is this just a N issue though? I couldn't reproduce the error from Slack from just a pairwise comparison based on the log outputs looking at the pairs tsv but is this created from the samples tsv instead?

## Slack Error

```
Unexpected Related Group 19 (somalier said these were related genomes but their filenames would indicate otherwise)
gds://production/analysis_data/SBJ01626/tso_ctdna_tumor_only/202208171fe7d4e9/L2201126/Results/PRJ221876_L2201126/PRJ221876_L2201126.bam subj=SBJ01626 lib=L2201126 r=0.75 n=6 shared hets=3 shared hom alts=0 base=PRJ221876_L2201126.bam
gds://production/analysis_data/SBJ01631/tso_ctdna_tumor_only/202204042c430a8c/L2200205/Results/PRJ220034_L2200205/PRJ220034_L2200205.bam subj=SBJ01631 lib=L2200205 r=0.833 n=8 shared hets=5 shared hom alts=1 base=PRJ220034_L2200205.bam
```


## Local testing

```
get_prefix_from_bam_file(){
 # Input bam path
 echo "s3://umccr-fingerprint-prod/fingerprints/$(echo -n "$1" | xxd -p | tr -d '\n')"
}

download_extraction_file(){
 # Output bam path
 wget --output-document "somalier_extract/$(basename $1).somalier" \
   "$(aws s3 presign "$(get_prefix_from_bam_file $1)")"
}
```


```
mkdir somalier_extract
download_extraction_file "${BAM_PATH_ONE}"
download_extraction_file "${BAM_PATH_TWO}"
```

Then relate

```
somalier relate somalier_extract/*
```

Yields

**Pairs.tsv**

```tsv
#sample_a	sample_b	relatedness	ibs0	ibs2	hom_concordance	hets_a	hets_b	hets_ab	shared_hets	hom_alts_a	hom_alts_b	shared_hom_alts	n	x_ibs0	x_ibs2	expected_relatedness
PRJ220034_L2200205	PRJ221876_L2201126	-0.022	9	59	0.000	194	42	91	17	212	45	18	125	0	0	-1.0
```

**Samples.tsv**

```tsv
#family_id	sample_id	paternal_id	maternal_id	sex	phenotype	original_pedigree_sex	gt_depth_mean	gt_depth_sd	depth_mean	depth_sd	ab_mean	ab_std	n_hom_ref	n_het	n_hom_alt	n_unknown	p_middling_ab	X_depth_mean	X_n	X_hom_ref	X_het	X_hom_alt	Y_depth_mean	Y_n
PRJ220034_L2200205	PRJ220034_L2200205	-9	-9	-9	-9	-9	354.7	423.0	14.0	105.4	-0.14	0.82	172	194	212	15891	0.000	565.34	29	15	2	12	0.00	0
PRJ221876_L2201126	PRJ221876_L2201126	-9	-9	-9	-9	-9	1254.0	1126.0	10.5	152.2	0.07	0.76	45	42	45	16337	0.000	0.00	0	0	0	0	0.00	0
```

**Comment by andrewpatto** [comment]
Thanks for this checking. So can we not actually reproduce the `n` that gets outputted into
`lib=L2201126 r=0.75 n=6`
?

**Comment by alexiswl** [comment]
I can if I run via holmes

## Code

<details>
<summary>Details</summary>

```bash
SERVICE_NAME="fingerprint"
CHECK_STEPS_ARN_KEY="checkStepsArn"
RELATEDNESS_THRESHOLD="0.4"

# From the unrelated group 19
BAM_PATH_ONE="gds://production/analysis_data/SBJ01626/tso_ctdna_tumor_only/202208171fe7d4e9/L2201126/Results/PRJ221876_L2201126/PRJ221876_L2201126.bam"
BAM_PATH_TWO="gds://production/analysis_data/SBJ01631/tso_ctdna_tumor_only/202204042c430a8c/L2200205/Results/PRJ220034_L2200205/PRJ220034_L2200205.bam"

fingerprint_service_id="$( \
  aws servicediscovery list-services \
    --output json | \
  jq --raw-output \
    --arg service_name "${SERVICE_NAME}" \
    '
      .Services[] |
      select(.Name=="fingerprint") |
      .Id
    ' \
)"
service_attributes_json_str="$( \
  aws servicediscovery list-instances \
    --output json \
    --service-id "${fingerprint_service_id}" | \
  jq --raw-output \
     '
       .Instances[] |
       .Attributes |
       to_entries
     ' \
)"
check_step_statemachine_arn="$( \
  jq --raw-output \
    --arg check_steps_arn_key "${CHECK_STEPS_ARN_KEY}" \
    '
      .[] |
      select(.key==$check_steps_arn_key) |
      .value
    ' \
    <<< "${service_attributes_json_str}" \
)"
echo "Generate check stepfunction input" 1>&2
check_step_cli_input_json_str="$( \
  jq --raw-output --null-input --compact-output \
    --arg relatedness_threshold "${RELATEDNESS_THRESHOLD}" \
    --arg input_bam_one "${BAM_PATH_ONE}" \
    --arg input_bam_two "${BAM_PATH_TWO}" \
    '
      {
        "input": {
          "indexes": [$input_bam_one, $input_bam_two],
          "relatednessThreshold": $relatedness_threshold | tonumber
        } | tojson
      }
    '
)"
check_step_run_instance_arn="$( \
  aws stepfunctions start-execution \
   --output json \
   --state-machine-arn "${check_step_statemachine_arn}" \
   --cli-input-json "${check_step_cli_input_json_str}" |
  jq --raw-output \
    '.executionArn'
)"

# Wait for check step to complete
# This should take around only 20 seconds
default_status="RUNNING"
while :; do
  # Get status
  current_execution_status="$( \
    aws stepfunctions describe-execution \
      --output json \
      --execution-arn "${check_step_run_instance_arn}" | \
    jq --raw-output \
      '.status' \
  )"

  # If still running then just sleep for a bit
  if [[ "${current_execution_status}" == "${default_status}" ]]; then
    sleep 10
    continue
  fi

  # Oooh, our status has changed...
  echo "Our check status has changed to ${current_execution_status}"
  break
done

aws stepfunctions describe-execution \
      --output json \
      --execution-arn "${check_step_run_instance_arn}" | \
    jq --raw-output \
      '.output | fromjson' 
```

</details>

## Output

<details>
<summary>Details</summary>

```json
[
  {},
  {
    "gds://production/analysis_data/SBJ01626/tso_ctdna_tumor_only/202208171fe7d4e9/L2201126/Results/PRJ221876_L2201126/PRJ221876_L2201126.bam": [
      {
        "file": "gds://production/analysis_data/SBJ02091/tso_ctdna_tumor_only/202205245ae2e876/L2200593/Results/MDX220141_L2200593/MDX220141_L2200593.bam",
        "relatedness": 0.476,
        "ibs0": 0,
        "ibs2": 11,
        "hom_concordance": 0.333,
        "hets_a": 42,
        "hets_b": 11,
        "hets_ab": 21,
        "shared_hets": 5,
        "hom_alts_a": 45,
        "hom_alts_b": 3,
        "shared_hom_alts": 1,
        "n": 22,
        "x_ibs0": 0,
        "x_ibs2": 0
      }
    ],
    "gds://production/analysis_data/SBJ01631/tso_ctdna_tumor_only/202204042c430a8c/L2200205/Results/PRJ220034_L2200205/PRJ220034_L2200205.bam": [
      {
        "file": "gds://production/analysis_data/SBJ02091/tso_ctdna_tumor_only/202205245ae2e876/L2200593/Results/MDX220141_L2200593/MDX220141_L2200593.bam",
        "relatedness": 0.72,
        "ibs0": 0,
        "ibs2": 14,
        "hom_concordance": 0.333,
        "hets_a": 194,
        "hets_b": 11,
        "hets_ab": 25,
        "shared_hets": 9,
        "hom_alts_a": 212,
        "hom_alts_b": 3,
        "shared_hom_alts": 1,
        "n": 21,
        "x_ibs0": 0,
        "x_ibs2": 0
      }
    ]
  },
  {
    "gds://production/analysis_data/SBJ01626/tso_ctdna_tumor_only/202208171fe7d4e9/L2201126/Results/PRJ221876_L2201126/PRJ221876_L2201126.bam": [
      {
        "file": "gds://production/analysis_data/SBJ02761/wgs_alignment_qc/20220828a5852f4e/L2201247__4_dragen/PRJ221788.bam",
        "relatedness": 0.4,
        "ibs0": 0,
        "ibs2": 10,
        "hom_concordance": 0.067,
        "hets_a": 42,
        "hets_b": 380,
        "hets_ab": 20,
        "shared_hets": 4,
        "hom_alts_a": 45,
        "hom_alts_b": 326,
        "shared_hom_alts": 3,
        "n": 22,
        "x_ibs0": 0,
        "x_ibs2": 0
      }
    ]
  },
  {
    "gds://production/analysis_data/SBJ01626/tso_ctdna_tumor_only/202208171fe7d4e9/L2201126/Results/PRJ221876_L2201126/PRJ221876_L2201126.bam": [
      {
        "file": "gds://production/analysis_data/SBJ02833/wgs_alignment_qc/2022100152b3a3b4/L2201376__4_dragen/PRJ221431.bam",
        "relatedness": 0.452,
        "ibs0": 1,
        "ibs2": 55,
        "hom_concordance": 0.378,
        "hets_a": 42,
        "hets_b": 6075,
        "hets_ab": 84,
        "shared_hets": 21,
        "hom_alts_a": 45,
        "hom_alts_b": 2501,
        "shared_hom_alts": 19,
        "n": 98,
        "x_ibs0": 0,
        "x_ibs2": 0
      }
    ]
  },
  {
    "gds://production/analysis_data/SBJ01626/tso_ctdna_tumor_only/202208171fe7d4e9/L2201126/Results/PRJ221876_L2201126/PRJ221876_L2201126.bam": [
      {
        "file": "gds://production/analysis_data/SBJ00006/tso_ctdna_tumor_only/202112161ba57b7f/L2101417/Results/NTC_ctTSO211110_L2101417/NTC_ctTSO211110_L2101417.bam",
        "relatedness": 0.5,
        "ibs0": 0,
        "ibs2": 1,
        "hom_concordance": 0,
        "hets_a": 42,
        "hets_b": 4,
        "hets_ab": 4,
        "shared_hets": 1,
        "hom_alts_a": 45,
        "hom_alts_b": 2,
        "shared_hom_alts": 0,
        "n": 3,
        "x_ibs0": 0,
        "x_ibs2": 0
      }
    ]
  },
  {
    "gds://production/analysis_data/SBJ01631/tso_ctdna_tumor_only/202204042c430a8c/L2200205/Results/PRJ220034_L2200205/PRJ220034_L2200205.bam": [
      {
        "file": "gds://production/analysis_data/SBJ02866/wgs_alignment_qc/20221010b5cccbb6/L2201472__4_dragen/PRJ222153.bam",
        "relatedness": 0.417,
        "ibs0": 0,
        "ibs2": 14,
        "hom_concordance": 0.033,
        "hets_a": 194,
        "hets_b": 269,
        "hets_ab": 24,
        "shared_hets": 5,
        "hom_alts_a": 212,
        "hom_alts_b": 240,
        "shared_hom_alts": 7,
        "n": 28,
        "x_ibs0": 0,
        "x_ibs2": 0
      }
    ]
  },
  {
    "gds://production/analysis_data/SBJ01626/tso_ctdna_tumor_only/202208171fe7d4e9/L2201126/Results/PRJ221876_L2201126/PRJ221876_L2201126.bam": [
      {
        "file": "gds://production/analysis_data/SBJ02865/wgs_alignment_qc/20221010f119fdf9/L2201468__2_dragen/MDX220289.bam",
        "relatedness": 0.4,
        "ibs0": 1,
        "ibs2": 8,
        "hom_concordance": -0.044,
        "hets_a": 42,
        "hets_b": 227,
        "hets_ab": 15,
        "shared_hets": 5,
        "hom_alts_a": 45,
        "hom_alts_b": 150,
        "shared_hom_alts": 0,
        "n": 14,
        "x_ibs0": 0,
        "x_ibs2": 0
      }
    ],
    "gds://production/analysis_data/SBJ01631/tso_ctdna_tumor_only/202204042c430a8c/L2200205/Results/PRJ220034_L2200205/PRJ220034_L2200205.bam": [
      {
        "file": "gds://production/analysis_data/SBJ02865/wgs_alignment_qc/20221010f119fdf9/L2201468__2_dragen/MDX220289.bam",
        "relatedness": 0.519,
        "ibs0": 0,
        "ibs2": 13,
        "hom_concordance": 0.04,
        "hets_a": 194,
        "hets_b": 227,
        "hets_ab": 27,
        "shared_hets": 7,
        "hom_alts_a": 212,
        "hom_alts_b": 150,
        "shared_hom_alts": 6,
        "n": 26,
        "x_ibs0": 0,
        "x_ibs2": 0
      }
    ]
  },
  {
    "gds://production/analysis_data/SBJ01631/tso_ctdna_tumor_only/202204042c430a8c/L2200205/Results/PRJ220034_L2200205/PRJ220034_L2200205.bam": [
      {
        "file": "gds://production/analysis_data/SBJ02731/wgs_alignment_qc/202209044ca8949a/L2201198__4_dragen/PRJ221766.bam",
        "relatedness": 0.667,
        "ibs0": 0,
        "ibs2": 8,
        "hom_concordance": 0.02,
        "hets_a": 194,
        "hets_b": 148,
        "hets_ab": 6,
        "shared_hets": 2,
        "hom_alts_a": 212,
        "hom_alts_b": 196,
        "shared_hom_alts": 4,
        "n": 10,
        "x_ibs0": 0,
        "x_ibs2": 0
      }
    ]
  },
  {
    "gds://production/analysis_data/SBJ01626/tso_ctdna_tumor_only/202208171fe7d4e9/L2201126/Results/PRJ221876_L2201126/PRJ221876_L2201126.bam": [
      {
        "file": "gds://production/analysis_data/SBJ01626/tso_ctdna_tumor_only/202208171fe7d4e9/L2201126/Results/PRJ221876_L2201126/PRJ221876_L2201126.bam",
        "relatedness": 1,
        "ibs0": 0,
        "ibs2": 132,
        "hom_concordance": 1,
        "hets_a": 42,
        "hets_b": 42,
        "hets_ab": 84,
        "shared_hets": 42,
        "hom_alts_a": 45,
        "hom_alts_b": 45,
        "shared_hom_alts": 45,
        "n": 132,
        "x_ibs0": 0,
        "x_ibs2": 0
      },
      {
        "file": "gds://production/analysis_data/SBJ01626/wgs_alignment_qc/20220226b47e2e00/L2200230__2_dragen/PRJ220470.bam",
        "relatedness": 1,
        "ibs0": 0,
        "ibs2": 120,
        "hom_concordance": 0.956,
        "hets_a": 42,
        "hets_b": 3679,
        "hets_ab": 66,
        "shared_hets": 33,
        "hom_alts_a": 45,
        "hom_alts_b": 5379,
        "shared_hom_alts": 43,
        "n": 120,
        "x_ibs0": 0,
        "x_ibs2": 0
      },
      {
        "file": "gds://production/analysis_data/SBJ01626/wgs_alignment_qc/20220226c81c7f9b/L2200243__3_dragen/PRJ220487.bam",
        "relatedness": 1,
        "ibs0": 0,
        "ibs2": 126,
        "hom_concordance": 0.933,
        "hets_a": 42,
        "hets_b": 6179,
        "hets_ab": 82,
        "shared_hets": 41,
        "hom_alts_a": 45,
        "hom_alts_b": 5264,
        "shared_hom_alts": 42,
        "n": 126,
        "x_ibs0": 0,
        "x_ibs2": 0
      }
    ],
    "gds://production/analysis_data/SBJ01631/tso_ctdna_tumor_only/202204042c430a8c/L2200205/Results/PRJ220034_L2200205/PRJ220034_L2200205.bam": [
      {
        "file": "gds://production/analysis_data/SBJ01631/tso_ctdna_tumor_only/202204042c430a8c/L2200205/Results/PRJ220034_L2200205/PRJ220034_L2200205.bam",
        "relatedness": 1,
        "ibs0": 0,
        "ibs2": 578,
        "hom_concordance": 1,
        "hets_a": 194,
        "hets_b": 194,
        "hets_ab": 388,
        "shared_hets": 194,
        "hom_alts_a": 212,
        "hom_alts_b": 212,
        "shared_hom_alts": 212,
        "n": 578,
        "x_ibs0": 0,
        "x_ibs2": 29
      }
    ]
  },
  {
    "gds://production/analysis_data/SBJ01626/tso_ctdna_tumor_only/202208171fe7d4e9/L2201126/Results/PRJ221876_L2201126/PRJ221876_L2201126.bam": [
      {
        "file": "gds://production/analysis_data/SBJ02523/wgs_alignment_qc/20220717f8d98c27/L2200874__4_dragen/PRJ221592.bam",
        "relatedness": 0.4,
        "ibs0": 2,
        "ibs2": 48,
        "hom_concordance": 0.267,
        "hets_a": 42,
        "hets_b": 1478,
        "hets_ab": 50,
        "shared_hets": 14,
        "hom_alts_a": 45,
        "hom_alts_b": 1140,
        "shared_hom_alts": 16,
        "n": 72,
        "x_ibs0": 0,
        "x_ibs2": 0
      }
    ]
  },
  {
    "gds://production/analysis_data/SBJ01626/tso_ctdna_tumor_only/202208171fe7d4e9/L2201126/Results/PRJ221876_L2201126/PRJ221876_L2201126.bam": [
      {
        "file": "gds://production/analysis_data/SBJ03119/wgs_alignment_qc/20230311f8a7de16/L2300285__1_dragen/PRJ230126.bam",
        "relatedness": 0.75,
        "ibs0": 0,
        "ibs2": 4,
        "hom_concordance": 0,
        "hets_a": 42,
        "hets_b": 44,
        "hets_ab": 8,
        "shared_hets": 3,
        "hom_alts_a": 45,
        "hom_alts_b": 48,
        "shared_hom_alts": 0,
        "n": 6,
        "x_ibs0": 0,
        "x_ibs2": 0
      }
    ],
    "gds://production/analysis_data/SBJ01631/tso_ctdna_tumor_only/202204042c430a8c/L2200205/Results/PRJ220034_L2200205/PRJ220034_L2200205.bam": [
      {
        "file": "gds://production/analysis_data/SBJ03119/wgs_alignment_qc/20230311f8a7de16/L2300285__1_dragen/PRJ230126.bam",
        "relatedness": 0.833,
        "ibs0": 0,
        "ibs2": 6,
        "hom_concordance": 0.021,
        "hets_a": 194,
        "hets_b": 44,
        "hets_ab": 12,
        "shared_hets": 5,
        "hom_alts_a": 212,
        "hom_alts_b": 48,
        "shared_hom_alts": 1,
        "n": 8,
        "x_ibs0": 0,
        "x_ibs2": 0
      },
      {
        "file": "gds://production/analysis_data/SBJ03120/wts_tumor_only/20230311fe07d009/L2300293_dragen/PRJ230134.bam",
        "relatedness": 0.421,
        "ibs0": 0,
        "ibs2": 8,
        "hom_concordance": 0.017,
        "hets_a": 194,
        "hets_b": 142,
        "hets_ab": 19,
        "shared_hets": 4,
        "hom_alts_a": 212,
        "hom_alts_b": 178,
        "shared_hom_alts": 3,
        "n": 19,
        "x_ibs0": 0,
        "x_ibs2": 0
      }
    ]
  }
]

```

</details>

**Comment by andrewpatto** [comment]
But I thought I got the N out of the CSVs! Where are my Ns coming from?

I do run it with env of  SOMALIER_REPORT_ALL_PAIRS: "1" - can you check that?

**Comment by andrewpatto** [comment]
I note my comment

```
// somalier will keep pairs of very low relatedness out of the output - but for our use cases we mind as well
// always include all output and use our own thresholds
```

which may be completely wrong.. I can certainly easily take out the ALL_PAIRS env

**Comment by alexiswl** [comment]
## Report all pairs

### Code
```bash
SOMALIER_REPORT_ALL_PAIRS="1" \
  somalier relate --output-prefix "report-all-pairs" somalier_extract/*
```

### Samples TSV

```tsv
#family_id	sample_id	paternal_id	maternal_id	sex	phenotype	original_pedigree_sex	gt_depth_mean	gt_depth_sd	depth_mean	depth_sd	ab_mean	ab_std	n_hom_ref	n_het	n_hom_alt	n_unknown	p_middling_ab	X_depth_mean	X_n	X_hom_ref	X_het	X_hom_alt	Y_depth_mean	Y_n
PRJ220034_L2200205	PRJ220034_L2200205	-9	-9	-9	-9	-9	354.7	423.0	14.0	105.4	-0.14	0.82	172	194	212	15891	0.000	565.34	29	15	2	12	0.00	0
PRJ221876_L2201126	PRJ221876_L2201126	-9	-9	-9	-9	-9	1254.0	1126.0	10.5	152.2	0.07	0.76	45	42	45	16337	0.000	0.00	0	0	0	0	0.00	0
```

### Pairs TSV

```tsv
#sample_a	sample_b	relatedness	ibs0	ibs2	hom_concordance	hets_a	hets_b	hets_ab	shared_hets	hom_alts_a	hom_alts_b	shared_hom_alts	n	x_ibs0	x_ibs2	expected_relatedness
PRJ220034_L2200205	PRJ221876_L2201126	-0.022	9	59	0.000	194	42	91	17	212	45	18	125	0	0	-1.0
```

## No report all pairs

### Code

```bash
somalier relate --output-prefix "no-report-all-pairs" somalier_extract/*
```

### Samples TSV

```tsv
#family_id	sample_id	paternal_id	maternal_id	sex	phenotype	original_pedigree_sex	gt_depth_mean	gt_depth_sd	depth_mean	depth_sd	ab_mean	ab_std	n_hom_ref	n_het	n_hom_alt	n_unknown	p_middling_ab	X_depth_mean	X_n	X_hom_ref	X_het	X_hom_alt	Y_depth_mean	Y_n
PRJ220034_L2200205	PRJ220034_L2200205	-9	-9	-9	-9	-9	354.7	423.0	14.0	105.4	-0.14	0.82	172	194	212	15891	0.000	565.34	29	15	2	12	0.00	0
PRJ221876_L2201126	PRJ221876_L2201126	-9	-9	-9	-9	-9	1254.0	1126.0	10.5	152.2	0.07	0.76	45	42	45	16337	0.000	0.00	0	0	0	0	0.00	0
```

### Pairs TSV

```tsv
#sample_a	sample_b	relatedness	ibs0	ibs2	hom_concordance	hets_a	hets_b	hets_ab	shared_hets	hom_alts_a	hom_alts_b	shared_hom_alts	n	x_ibs0	x_ibs2	expected_relatedness
PRJ220034_L2200205	PRJ221876_L2201126	-0.022	9	59	0.000	194	42	91	17	212	45	18	125	0	0	-1.0
```

## Conclusion

Are these the same outputs?

```bash
md5sum *.samples.tsv
```

```
29e17aa9cba86066f8f6621a5f72453a  no-report-all-pairs.samples.tsv
29e17aa9cba86066f8f6621a5f72453a  report-all-pairs.samples.tsv
```


```bash
md5sum *.pairs.tsv
```

```
afba5dbe33433494c87c8419114435d0  no-report-all-pairs.pairs.tsv
afba5dbe33433494c87c8419114435d0  report-all-pairs.pairs.tsv
```

**Comment by andrewpatto** [comment]
The output from a direct lambda invoke on those two files

```
2023-03-21T00:10:01.277Z	f7c000ad-4b11-42c7-833a-d5922147051b	INFO	samples #family_id	sample_id	paternal_id	maternal_id	sex	phenotype	original_pedigree_sex	gt_depth_mean	gt_depth_sd	depth_mean	depth_sd	ab_mean	ab_std	n_hom_ref	n_het	n_hom_alt	n_unknown	p_middling_ab	X_depth_mean	X_n	X_hom_ref	X_het	X_hom_alt	Y_depth_mean	Y_n
2023-03-21T00:10:01.277Z	f7c000ad-4b11-42c7-833a-d5922147051b	INFO	samples 000000000000000000	000000000000000000	-9	-9	-9	-9	-9	354.7	423.0	14.0	105.4	-0.14	0.82	172	194	212	15891	0.000	565.34	29	15	2	12	0.00	0
2023-03-21T00:10:01.277Z	f7c000ad-4b11-42c7-833a-d5922147051b	INFO	samples 000000000000000001	000000000000000001	-9	-9	-9	-9	-9	354.7	423.0	14.0	105.4	-0.14	0.82	172	194	212	15891	0.000	565.34	29	15	2	12	0.00	0
2023-03-21T00:10:01.277Z	f7c000ad-4b11-42c7-833a-d5922147051b	INFO	samples 
2023-03-21T00:10:01.277Z	f7c000ad-4b11-42c7-833a-d5922147051b	INFO	pairs #sample_a	sample_b	relatedness	ibs0	ibs2	hom_concordance	hets_a	hets_b	hets_ab	shared_hets	hom_alts_a	hom_alts_b	shared_hom_alts	n	x_ibs0	x_ibs2	expected_relatedness
2023-03-21T00:10:01.277Z	f7c000ad-4b11-42c7-833a-d5922147051b	INFO	pairs 000000000000000000	000000000000000001	1.000	0	578	1.000	194	194	388	194	212	212	212	578	0	29	-1.0
2023-03-21T00:10:01.277Z	f7c000ad-4b11-42c7-833a-d5922147051b	INFO	pairs 
2023-03-21T00:10:01.277Z	f7c000ad-4b11-42c7-833a-d5922147051b	INFO	Extracting matches for index sample id 000000000000000000 which = fingerprints-local-n-test/73333a2f2f50524a3232303033345f4c323230303230352e62616d
2023-03-21T00:10:01.283Z	f7c000ad-4b11-42c7-833a-d5922147051b	INFO	Match at 1 to sample id 000000000000000001 which = fingerprints-local-n-test/73333a2f2f50524a3232303033345f4c323230303230352e62616d
```

**Comment by andrewpatto** [comment]
```
2023-03-21T00:15:59.772Z	5be4e5b7-6b99-40c2-8743-98abad1cfeff	INFO	samples #family_id	sample_id	paternal_id	maternal_id	sex	phenotype	original_pedigree_sex	gt_depth_mean	gt_depth_sd	depth_mean	depth_sd	ab_mean	ab_std	n_hom_ref	n_het	n_hom_alt	n_unknown	p_middling_ab	X_depth_mean	X_n	X_hom_ref	X_het	X_hom_alt	Y_depth_mean	Y_n
2023-03-21T00:15:59.772Z	5be4e5b7-6b99-40c2-8743-98abad1cfeff	INFO	samples 000000000000000000	000000000000000000	-9	-9	-9	-9	-9	354.7	423.0	14.0	105.4	-0.14	0.82	172	194	212	15891	0.000	565.34	29	15	2	12	0.00	0
2023-03-21T00:15:59.772Z	5be4e5b7-6b99-40c2-8743-98abad1cfeff	INFO	samples 000000000000000001	000000000000000001	-9	-9	-9	-9	-9	1254.0	1126.0	10.5	152.2	0.07	0.76	45	42	45	16337	0.000	0.00	0	0	0	0	0.00	0
2023-03-21T00:15:59.772Z	5be4e5b7-6b99-40c2-8743-98abad1cfeff	INFO	samples 
2023-03-21T00:15:59.772Z	5be4e5b7-6b99-40c2-8743-98abad1cfeff	INFO	pairs #sample_a	sample_b	relatedness	ibs0	ibs2	hom_concordance	hets_a	hets_b	hets_ab	shared_hets	hom_alts_a	hom_alts_b	shared_hom_alts	n	x_ibs0	x_ibs2	expected_relatedness
2023-03-21T00:15:59.772Z	5be4e5b7-6b99-40c2-8743-98abad1cfeff	INFO	pairs 000000000000000000	000000000000000001	-0.022	9	59	0.000	194	42	91	17	212	45	18	125	0	0	-1.0
2023-03-21T00:15:59.772Z	5be4e5b7-6b99-40c2-8743-98abad1cfeff	INFO	pairs 
2023-03-21T00:15:59.772Z	5be4e5b7-6b99-40c2-8743-98abad1cfeff	INFO	Extracting matches for index sample id 000000000000000000 which = fingerprints-local-n-test/73333a2f2f50524a3232303033345f4c323230303230352e62616d
2023-03-21T00:15:59.776Z	5be4e5b7-6b99-40c2-8743-98abad1cfeff	INFO	Removing 000000000000000000.somalier from working directory
2023-03-21T00:15:59.776Z	5be4e5b7-6b99-40c2-8743-98abad1cfeff	INFO	Removing 000000000000000001.somalier from working directory
2023-03-21T00:15:59.776Z	5be4e5b7-6b99-40c2-8743-98abad1cfeff	INFO	Removing somalier.pairs.tsv from working directory
2023-03-21T00:15:59.776Z	5be4e5b7-6b99-40c2-8743-98abad1cfeff	INFO	Removing somalier.samples.tsv from working directory
```

**Comment by andrewpatto** [comment]
Ok I think the check function is executing the same as when you run locally. So at least there is no fundamental flaw there.

I think its likely something to do with the logic in the Slack notifier - which is a bit hairy.. I think we should remove these low N matches anyhow - even if it turns out there is a logic bug in the Slack notifier

**Pull request merged**
